"""empty message

Revision ID: 620fb0ec75ed
Revises: bb5ff40a02ea
Create Date: 2021-06-02 12:58:34.812987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620fb0ec75ed'
down_revision = 'bb5ff40a02ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('room', sa.String(length=500), nullable=True))
    op.add_column('chat_history', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'username')
    op.drop_column('chat_history', 'room')
    # ### end Alembic commands ###
